"""added foreign keys to Review

Revision ID: 4955e3ee8c3e
Revises: a10ffe35ac63
Create Date: 2024-04-04 18:39:04.791552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4955e3ee8c3e'
down_revision = 'a10ffe35ac63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_item_id_items'), 'reviews', 'items', ['item_id'], ['id'])
    op.create_foreign_key(op.f('fk_reviews_customer_id_customers'), 'reviews', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_customer_id_customers'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('fk_reviews_item_id_items'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'item_id')
    op.drop_column('reviews', 'customer_id')
    # ### end Alembic commands ###
